// GENERATED by urcapgen — do not edit; regenerate with `urcapgen gen`.
package @@PACKAGE@@;

import com.ur.urcap.api.contribution.ViewAPIProvider;
import com.ur.urcap.api.domain.data.DataModel;
import com.ur.urcap.api.domain.userinteraction.UserInteraction;
import com.ur.urcap.api.domain.userinteraction.keyboard.KeyboardInputCallback;
import com.ur.urcap.api.domain.userinteraction.keyboard.KeyboardNumberInput;
import com.ur.urcap.api.domain.userinteraction.keyboard.KeyboardTextInput;
import com.ur.urcap.api.domain.value.Pose;
import com.ur.urcap.api.domain.value.jointposition.JointPositions;
import com.ur.urcap.api.domain.value.simple.Angle;
import com.ur.urcap.api.domain.value.simple.Length;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * A node's fields as a PolyScope 5 form: number and text fields open the pendant's own
 * keypad, booleans are check boxes, choices drop-downs, poses a "Set position" button that
 * opens PolyScope's move screen. Values live in the node's DataModel; {@link Store} decides
 * how a change is recorded (a program node wraps it in an undoable change).
 */
public final class Form {
    /** One field of the spec. */
    public static final class Def {
        public final String key;
        public final String type;
        public final String label;
        public final String unit;
        public final String help;
        public final Double min;
        public final Double max;
        public final Object def;
        public final String[] optionValues;
        public final String[] optionLabels;

        public Def(String key, String type, String label, String unit, String help, Double min, Double max,
                Object def, String[] optionValues, String[] optionLabels) {
            this.key = key;
            this.type = type;
            this.label = label;
            this.unit = unit;
            this.help = help;
            this.min = min;
            this.max = max;
            this.def = def;
            this.optionValues = optionValues;
            this.optionLabels = optionLabels;
        }
    }

    /** Where a change goes. */
    public interface Store {
        DataModel model();

        void change(Runnable r);
    }

    // -- values ---------------------------------------------------------------------------------

    /** A field's current value from the model (its default when unset), as the template sees it. */
    public static Object get(DataModel m, Def d) {
        switch (d.type) {
            case "int":
                return m.get(d.key, ((Number) d.def).intValue());
            case "float":
                return m.get(d.key, ((Number) d.def).doubleValue());
            case "bool":
                return m.get(d.key, ((Boolean) d.def).booleanValue());
            case "pose":
                return m.get(d.key, (double[]) d.def);
            default:
                return m.get(d.key, (String) d.def);
        }
    }

    public static void put(DataModel m, Def d, Object v) {
        switch (d.type) {
            case "int":
                m.set(d.key, ((Number) v).intValue());
                break;
            case "float":
                m.set(d.key, ((Number) v).doubleValue());
                break;
            case "bool":
                m.set(d.key, ((Boolean) v).booleanValue());
                break;
            case "pose":
                m.set(d.key, (double[]) v);
                break;
            default:
                m.set(d.key, (String) v);
        }
    }

    public static Map<String, ScriptTemplate.Value> values(DataModel m, List<Def> defs) {
        Map<String, ScriptTemplate.Value> out = new LinkedHashMap<String, ScriptTemplate.Value>();
        for (Def d : defs) {
            out.put(d.key, new ScriptTemplate.Value(d.type, get(m, d)));
        }
        return out;
    }

    /** Why the values are not usable (the spec's min/max, options), or null. */
    public static String problem(DataModel m, List<Def> defs) {
        for (Def d : defs) {
            Object v = get(m, d);
            if ("int".equals(d.type) || "float".equals(d.type)) {
                double x = ((Number) v).doubleValue();
                if (Double.isNaN(x) || Double.isInfinite(x)) {
                    return d.label + ": not a number";
                }
                if (d.min != null && x < d.min) {
                    return d.label + ": at least " + fmt(d.min) + unit(d);
                }
                if (d.max != null && x > d.max) {
                    return d.label + ": at most " + fmt(d.max) + unit(d);
                }
            } else if ("string".equals(d.type)) {
                String s = (String) v;
                if (s.indexOf('"') >= 0 || s.indexOf('\n') >= 0 || s.indexOf('\r') >= 0) {
                    return d.label + ": no double quotes or line breaks";
                }
            } else if ("choice".equals(d.type)) {
                boolean found = false;
                for (String o : d.optionValues) {
                    found |= o.equals(v);
                }
                if (!found) {
                    return d.label + ": not one of the options";
                }
            }
        }
        return null;
    }

    private static String unit(Def d) {
        return d.unit.isEmpty() ? "" : " " + d.unit;
    }

    /** A number as the JS presenter shows it: no trailing ".0" on whole numbers. */
    static String fmt(double x) {
        return x == Math.rint(x) && Math.abs(x) < 1e15 ? Long.toString((long) x) : Double.toString(x);
    }

    static String show(Def d, Object v) {
        if ("float".equals(d.type)) {
            return ScriptTemplate.number(((Number) v).doubleValue());
        }
        if ("pose".equals(d.type)) {
            return ScriptTemplate.literal(new ScriptTemplate.Value("pose", v));
        }
        return String.valueOf(v);
    }

    // -- the form -------------------------------------------------------------------------------

    private final ViewAPIProvider api;
    private final List<Def> defs;
    private final Map<String, JComponent> inputs = new LinkedHashMap<String, JComponent>();
    private final JLabel status = new JLabel(" ");
    private Store store;
    private boolean refreshing;

    public Form(ViewAPIProvider api, List<Def> defs) {
        this.api = api;
        this.defs = defs;
    }

    private UserInteraction ui() {
        return api.getUserInterfaceAPI().getUserInteraction();
    }

    /** Lays the fields out in {@code panel}, two columns: label, input (+ help under it). */
    public void build(JPanel panel, String title, String description) {
        panel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.anchor = GridBagConstraints.NORTHWEST;
        c.insets = new Insets(4, 4, 4, 12);
        c.gridy = 0;
        c.gridx = 0;
        c.gridwidth = 2;
        JLabel head = new JLabel(title);
        head.setFont(head.getFont().deriveFont(Font.BOLD, 20f));
        panel.add(head, c);
        if (!description.isEmpty()) {
            c.gridy++;
            panel.add(new JLabel("<html><div style='width:560px'>" + esc(description) + "</div></html>"), c);
        }
        c.gridwidth = 1;
        for (final Def d : defs) {
            c.gridy++;
            c.gridx = 0;
            c.weightx = 0;
            c.fill = GridBagConstraints.NONE;
            JLabel l = new JLabel(d.label + (d.unit.isEmpty() ? "" : " (" + d.unit + ")"));
            l.setFont(l.getFont().deriveFont(16f));
            panel.add(l, c);
            c.gridx = 1;
            JComponent input = input(d);
            inputs.put(d.key, input);
            panel.add(input, c);
            if (!d.help.isEmpty()) {
                c.gridy++;
                JLabel h = new JLabel(d.help);
                h.setForeground(Color.GRAY);
                panel.add(h, c);
            }
        }
        c.gridy++;
        c.gridx = 0;
        c.gridwidth = 2;
        status.setForeground(new Color(0xB0, 0x30, 0x30));
        panel.add(status, c);
    }

    /** The form's status line (validation messages); a hook may write to it too. */
    public JLabel status() {
        return status;
    }

    private JComponent input(final Def d) {
        if ("bool".equals(d.type)) {
            final JCheckBox box = new JCheckBox();
            box.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!refreshing) {
                        set(d, box.isSelected());
                    }
                }
            });
            return box;
        }
        if ("choice".equals(d.type)) {
            final JComboBox<String> combo = new JComboBox<String>(d.optionLabels);
            combo.setPreferredSize(new Dimension(260, 36));
            combo.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int i = combo.getSelectedIndex();
                    if (!refreshing && i >= 0) {
                        set(d, d.optionValues[i]);
                    }
                }
            });
            return combo;
        }
        if ("pose".equals(d.type)) {
            JPanel row = new JPanel();
            final JLabel shown = new JLabel();
            JButton teach = new JButton("Set position");
            teach.setPreferredSize(new Dimension(160, 36));
            teach.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    teach(d);
                }
            });
            row.add(shown);
            row.add(teach);
            row.putClientProperty("shown", shown);
            return row;
        }
        final JTextField field = new JTextField(14);
        field.setEditable(false);
        field.setPreferredSize(new Dimension(260, 36));
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.GRAY), BorderFactory.createEmptyBorder(2, 8, 2, 8)));
        field.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                ask(d, field);
            }
        });
        return field;
    }

    private void ask(final Def d, JTextField field) {
        if (store == null) {
            return;
        }
        Object now = get(store.model(), d);
        if ("int".equals(d.type)) {
            KeyboardNumberInput<Integer> kb = ui().getKeyboardInputFactory().createIntegerKeypadInput();
            kb.setInitialValue(((Number) now).intValue());
            kb.show(field, new KeyboardInputCallback<Integer>() {
                @Override
                public void onOk(Integer value) {
                    if (value != null) {
                        set(d, value);
                    }
                }
            });
        } else if ("float".equals(d.type)) {
            KeyboardNumberInput<Double> kb = ui().getKeyboardInputFactory().createDoubleKeypadInput();
            kb.setInitialValue(((Number) now).doubleValue());
            kb.show(field, new KeyboardInputCallback<Double>() {
                @Override
                public void onOk(Double value) {
                    if (value != null) {
                        set(d, value);
                    }
                }
            });
        } else {
            KeyboardTextInput kb = ui().getKeyboardInputFactory().createStringKeyboardInput();
            kb.setInitialValue((String) now);
            kb.show(field, new KeyboardInputCallback<String>() {
                @Override
                public void onOk(String value) {
                    if (value != null) {
                        set(d, value.replace("\"", "").replace("\n", " ").replace("\r", ""));
                    }
                }
            });
        }
    }

    @SuppressWarnings("deprecation") // RobotPositionCallback2 replaced it in 5.8; this one runs on every 5.x
    private void teach(final Def d) {
        // named in full: Java 8 warns on the import of a deprecated class, which no annotation reaches
        ui().getUserDefinedRobotPosition(new com.ur.urcap.api.domain.userinteraction.RobotPositionCallback() {
            @Override
            public void onOk(Pose pose, JointPositions q) {
                set(d, pose.toArray(Length.Unit.M, Angle.Unit.RAD));
            }
        });
    }

    private void set(final Def d, final Object v) {
        if (store == null) {
            return;
        }
        if (("int".equals(d.type) || "float".equals(d.type))) {
            double x = ((Number) v).doubleValue();
            if ((d.min != null && x < d.min) || (d.max != null && x > d.max)) {
                status.setText(d.label + ": " + (d.min != null ? fmt(d.min) : "…") + " to "
                        + (d.max != null ? fmt(d.max) : "…") + unit(d));
                return;
            }
        }
        store.change(new Runnable() {
            @Override
            public void run() {
                put(store.model(), d, v);
            }
        });
        refresh(store);
    }

    /** Shows the model's values; call from the contribution's openView. */
    public void refresh(Store s) {
        this.store = s;
        refreshing = true;
        try {
            for (Def d : defs) {
                Object v = get(s.model(), d);
                JComponent in = inputs.get(d.key);
                if (in instanceof JCheckBox) {
                    ((JCheckBox) in).setSelected(Boolean.TRUE.equals(v));
                } else if (in instanceof JComboBox) {
                    for (int i = 0; i < d.optionValues.length; i++) {
                        if (d.optionValues[i].equals(v)) {
                            ((JComboBox<?>) in).setSelectedIndex(i);
                        }
                    }
                } else if (in instanceof JTextField) {
                    ((JTextField) in).setText(show(d, v));
                } else if (in instanceof JPanel) {
                    ((JLabel) in.getClientProperty("shown")).setText(show(d, v));
                }
            }
            String why = problem(s.model(), defs);
            status.setText(why == null ? " " : why);
        } finally {
            refreshing = false;
        }
    }

    private static String esc(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
