// GENERATED by urcapgen — do not edit; regenerate with `urcapgen gen`.
package @@PACKAGE@@;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The URScript template language (urcapgen/scripttpl.py is the specification; urcapgen
 * parity tests hold this port and urcapgen-runtime.js to it). Java 8, no dependencies.
 */
public final class ScriptTemplate {
    /** A field's value with its spec type: int, float, bool, string, choice, pose. */
    public static final class Value {
        final String type;
        final Object value;

        public Value(String type, Object value) {
            this.type = type;
            this.value = value;
        }

        public String type() {
            return type;
        }

        public double asDouble() {
            return ((Number) value).doubleValue();
        }

        public int asInt() {
            return ((Number) value).intValue();
        }

        public boolean asBool() {
            return Boolean.TRUE.equals(value);
        }

        /** A string's or a choice's value (a choice: the option's value, not its label). */
        public String asString() {
            return String.valueOf(value);
        }

        public double[] asPose() {
            return ((double[]) value).clone();
        }

        /** The value as a URScript literal, the way {@code {{key}}} writes it. */
        public String literal() {
            return ScriptTemplate.literal(this);
        }
    }

    private static final Pattern STANDALONE = Pattern.compile("(?m)^[ \\t]*(\\{\\{[#^/!][^}]*\\}\\})[ \\t]*\\r?\\n");
    private static final Pattern TAG = Pattern.compile("\\{\\{([#^/!]?)\\s*([^}]*?)\\s*\\}\\}");
    private static final Pattern NAME = Pattern.compile("[a-z][a-z0-9_]*");

    private ScriptTemplate() {
    }

    public static String number(double x) {
        String s = new BigDecimal(x).setScale(6, RoundingMode.HALF_UP).toPlainString();
        if (s.indexOf('.') >= 0) {
            int end = s.length();
            while (s.charAt(end - 1) == '0') {
                end--;
            }
            s = s.substring(0, end);
            if (s.endsWith(".")) {
                s = s + "0";
            }
        } else {
            s = s + ".0";
        }
        return "-0.0".equals(s) ? "0.0" : s;
    }

    private static double num(Object v) {
        return ((Number) v).doubleValue();
    }

    public static String literal(Value v) {
        switch (v.type) {
            case "int":
                return Long.toString(Math.round(num(v.value)));
            case "float":
                return number(num(v.value));
            case "bool":
                return Boolean.TRUE.equals(v.value) ? "True" : "False";
            case "string": {
                String s = String.valueOf(v.value);
                if (s.indexOf('"') >= 0 || s.indexOf('\n') >= 0 || s.indexOf('\r') >= 0) {
                    throw new IllegalArgumentException("a string value cannot hold a double quote or a line break");
                }
                return "\"" + s + "\"";
            }
            case "choice":
                return String.valueOf(v.value);
            case "pose": {
                double[] p = (double[]) v.value;
                if (p.length != 6) {
                    throw new IllegalArgumentException("a pose has six numbers");
                }
                StringBuilder b = new StringBuilder("p[");
                for (int i = 0; i < 6; i++) {
                    b.append(i == 0 ? "" : ", ").append(number(p[i]));
                }
                return b.append(']').toString();
            }
            default:
                throw new IllegalArgumentException("unknown field type " + v.type);
        }
    }

    public static String raw(Value v) {
        if ("bool".equals(v.type)) {
            return Boolean.TRUE.equals(v.value) ? "true" : "false";
        }
        if ("string".equals(v.type) || "choice".equals(v.type)) {
            return String.valueOf(v.value);
        }
        return literal(v);
    }

    public static boolean truthy(Value v) {
        if ("bool".equals(v.type)) {
            return Boolean.TRUE.equals(v.value);
        }
        if ("int".equals(v.type) || "float".equals(v.type)) {
            return num(v.value) != 0.0;
        }
        if ("string".equals(v.type) || "choice".equals(v.type)) {
            return !String.valueOf(v.value).isEmpty();
        }
        return true;
    }

    private static final class Node {
        final String kind; // text | var | section
        final String text;
        final boolean inverted;
        final String eq;
        final List<Node> children = new ArrayList<Node>();
        final String name;

        Node(String kind, String text, String name, boolean inverted, String eq) {
            this.kind = kind;
            this.text = text;
            this.name = name;
            this.inverted = inverted;
            this.eq = eq;
        }
    }

    private static List<Node> parse(String template) {
        String text = STANDALONE.matcher(template).replaceAll("$1");
        List<Node> root = new ArrayList<Node>();
        List<List<Node>> stack = new ArrayList<List<Node>>();
        List<String> open = new ArrayList<String>();
        stack.add(root);
        open.add("");
        int pos = 0;
        Matcher m = TAG.matcher(text);
        while (m.find()) {
            List<Node> top = stack.get(stack.size() - 1);
            if (m.start() > pos) {
                top.add(new Node("text", text.substring(pos, m.start()), null, false, null));
            }
            pos = m.end();
            String sigil = m.group(1);
            String body = m.group(2);
            if ("!".equals(sigil)) {
                continue;
            }
            if ("#".equals(sigil) || "^".equals(sigil)) {
                int at = body.indexOf('=');
                String name = (at < 0 ? body : body.substring(0, at)).trim();
                String eq = at < 0 ? null : body.substring(at + 1).trim();
                if (!NAME.matcher(name).matches()) {
                    throw new IllegalArgumentException("bad section name " + name);
                }
                Node s = new Node("section", null, name, "^".equals(sigil), eq);
                top.add(s);
                stack.add(s.children);
                open.add(name);
                continue;
            }
            if ("/".equals(sigil)) {
                int at = body.indexOf('=');
                String name = (at < 0 ? body : body.substring(0, at)).trim();
                if (stack.size() == 1 || !open.get(open.size() - 1).equals(name)) {
                    throw new IllegalArgumentException("{{/" + name + "}} closes nothing open");
                }
                stack.remove(stack.size() - 1);
                open.remove(open.size() - 1);
                continue;
            }
            if (!NAME.matcher(body).matches()) {
                throw new IllegalArgumentException("bad variable {{" + body + "}}");
            }
            top.add(new Node("var", null, body, false, null));
        }
        if (stack.size() != 1) {
            throw new IllegalArgumentException("{{#" + open.get(open.size() - 1) + "}} is never closed");
        }
        if (pos < text.length()) {
            root.add(new Node("text", text.substring(pos), null, false, null));
        }
        return root;
    }

    private static Value get(Map<String, Value> values, String name) {
        Value v = values.get(name);
        if (v == null) {
            throw new IllegalArgumentException("no field " + name);
        }
        return v;
    }

    private static void walk(List<Node> nodes, Map<String, Value> values, boolean display, StringBuilder out) {
        for (Node n : nodes) {
            if ("text".equals(n.kind)) {
                out.append(n.text);
            } else if ("var".equals(n.kind)) {
                Value v = get(values, n.name);
                out.append(display && "string".equals(v.type) ? String.valueOf(v.value) : literal(v));
            } else {
                Value v = get(values, n.name);
                boolean hit = n.eq == null ? truthy(v) : raw(v).equals(n.eq);
                if (hit != n.inverted) {
                    walk(n.children, values, display, out);
                }
            }
        }
    }

    public static String render(String template, Map<String, Value> values) {
        return render(template, values, false);
    }

    /** {@code display}: for a node's label, not URScript — strings without their quotes. */
    public static String render(String template, Map<String, Value> values, boolean display) {
        StringBuilder out = new StringBuilder();
        walk(parse(template), values, display, out);
        return out.toString();
    }

    /** The rendered script's lines without indentation, empty ones dropped. */
    public static List<String> lines(String script) {
        List<String> out = new ArrayList<String>();
        for (String line : script.split("\r?\n", -1)) {
            String t = line.trim();
            if (!t.isEmpty()) {
                out.add(t);
            }
        }
        return out;
    }
}
