// GENERATED by urcapgen — do not edit; regenerate with `urcapgen gen`.
//
// The URScript template language (urcapgen/scripttpl.py is the specification; urcapgen's
// parity tests hold this port and ScriptTemplate.java to it), the threads.js worker protocol
// PolyScope X speaks to behavior workers, and small helpers the generated presenters share.
// Loaded by importScripts() in workers and by a <script> tag in the page; defines
// self.Urcapgen. No dependencies, no build step.
//
// Every URCap's presenters share PolyScope X's page, and two URCaps may carry different
// urcapgen versions: each version registers itself in self.UrcapgenRuntimes[version] and the
// generated code uses its own. self.Urcapgen is the last one loaded (for hooks; its API is
// stable across versions).
(function (root) {
  "use strict";
  const VERSION = "@@VERSION@@";
  root.UrcapgenRuntimes = root.UrcapgenRuntimes || {};
  if (root.UrcapgenRuntimes[VERSION]) return;

  const STANDALONE = /^[ \t]*(\{\{[#^/!][^}]*\}\})[ \t]*\r?\n/gm;
  const TAG = /\{\{([#^/!]?)\s*([^}]*?)\s*\}\}/g;
  const NAME = /^[a-z][a-z0-9_]*$/;

  function number(x) {
    // toFixed rounds the exact binary value half away from zero, like Python's
    // Decimal(x).quantize(ROUND_HALF_UP) and Java's new BigDecimal(x).setScale(6, HALF_UP).
    let s = Number(x).toFixed(6);
    if (s.indexOf(".") >= 0) {
      s = s.replace(/0+$/, "");
      if (s.endsWith(".")) s += "0";
    } else {
      s += ".0";
    }
    return s === "-0.0" ? "0.0" : s;
  }

  function literal(type, value) {
    switch (type) {
      case "int": return String(Math.round(Number(value)));
      case "float": return number(value);
      case "bool": return value === true ? "True" : "False";
      case "string": {
        const s = String(value);
        if (/["\n\r]/.test(s)) throw new Error("a string value cannot hold a double quote or a line break");
        return `"${s}"`;
      }
      case "choice": return String(value);
      case "pose": {
        if (!Array.isArray(value) || value.length !== 6) throw new Error("a pose has six numbers");
        return "p[" + value.map(number).join(", ") + "]";
      }
      default: throw new Error(`unknown field type ${type}`);
    }
  }

  function raw(type, value) {
    if (type === "bool") return value === true ? "true" : "false";
    if (type === "string" || type === "choice") return String(value);
    return literal(type, value);
  }

  function truthy(type, value) {
    if (type === "bool") return value === true;
    if (type === "int" || type === "float") return Number(value) !== 0;
    if (type === "string" || type === "choice") return String(value) !== "";
    return true;
  }

  function parse(template) {
    const text = template.replace(STANDALONE, "$1");
    const root = [];
    const stack = [{ name: "", children: root }];
    let pos = 0;
    TAG.lastIndex = 0;
    let m;
    while ((m = TAG.exec(text)) !== null) {
      const top = stack[stack.length - 1].children;
      if (m.index > pos) top.push({ kind: "text", text: text.slice(pos, m.index) });
      pos = m.index + m[0].length;
      const sigil = m[1];
      const body = m[2];
      if (sigil === "!") continue;
      if (sigil === "#" || sigil === "^") {
        const at = body.indexOf("=");
        const name = (at < 0 ? body : body.slice(0, at)).trim();
        const eq = at < 0 ? null : body.slice(at + 1).trim();
        if (!NAME.test(name)) throw new Error(`bad section name ${name}`);
        const s = { kind: "section", name, inverted: sigil === "^", eq, children: [] };
        top.push(s);
        stack.push(s);
        continue;
      }
      if (sigil === "/") {
        const at = body.indexOf("=");
        const name = (at < 0 ? body : body.slice(0, at)).trim();
        if (stack.length === 1 || stack[stack.length - 1].name !== name) throw new Error(`{{/${name}}} closes nothing open`);
        stack.pop();
        continue;
      }
      if (!NAME.test(body)) throw new Error(`bad variable {{${body}}}`);
      top.push({ kind: "var", name: body });
    }
    if (stack.length !== 1) throw new Error(`{{#${stack[stack.length - 1].name}}} is never closed`);
    if (pos < text.length) root.push({ kind: "text", text: text.slice(pos) });
    return root;
  }

  // values: {key: {type, value}}; display: for a node's label — strings without their quotes
  function render(template, values, display) {
    const out = [];
    const get = (name) => {
      if (!Object.prototype.hasOwnProperty.call(values, name)) throw new Error(`no field ${name}`);
      return values[name];
    };
    const walk = (nodes) => {
      for (const n of nodes) {
        if (n.kind === "text") out.push(n.text);
        else if (n.kind === "var") { const v = get(n.name); out.push(display && v.type === "string" ? String(v.value) : literal(v.type, v.value)); }
        else {
          const v = get(n.name);
          const hit = n.eq === null ? truthy(v.type, v.value) : raw(v.type, v.value) === n.eq;
          if (hit !== n.inverted) walk(n.children);
        }
      }
    };
    walk(parse(template));
    return out.join("");
  }

  function lines(script) {
    return script.split(/\r?\n/).map((l) => l.trim()).filter((l) => l !== "");
  }

  // -- node values ---------------------------------------------------------------------------

  // The saved parameters of a node, completed with the spec's defaults (a node saved by an
  // older version lacks newer fields) and coerced to each field's type.
  function valuesOf(fields, params) {
    const p = params || {};
    const out = {};
    for (const f of fields) {
      let v = Object.prototype.hasOwnProperty.call(p, f.key) ? p[f.key] : f.default;
      if (f.type === "int") v = Math.round(Number(v));
      else if (f.type === "float") v = Number(v);
      else if (f.type === "bool") v = v === true;
      else if (f.type === "string" || f.type === "choice") v = String(v);
      else if (f.type === "pose") v = Array.isArray(v) && v.length === 6 ? v.map(Number) : f.default.slice();
      out[f.key] = v;
    }
    return out;
  }

  function typed(fields, vals) {
    const out = {};
    for (const f of fields) out[f.key] = { type: f.type, value: vals[f.key] };
    return out;
  }

  // Why the values are not usable, or null: the generated validator.
  function problem(fields, vals) {
    for (const f of fields) {
      const v = vals[f.key];
      if (f.type === "int" || f.type === "float") {
        if (!Number.isFinite(v)) return `${f.label}: not a number`;
        if (f.min !== undefined && v < f.min) return `${f.label}: at least ${f.min}${f.unit ? " " + f.unit : ""}`;
        if (f.max !== undefined && v > f.max) return `${f.label}: at most ${f.max}${f.unit ? " " + f.unit : ""}`;
      } else if (f.type === "string") {
        if (/["\n\r]/.test(v)) return `${f.label}: no double quotes or line breaks`;
      } else if (f.type === "choice") {
        if (!f.options.some((o) => o.value === v)) return `${f.label}: not one of the options`;
      } else if (f.type === "pose") {
        if (!v.every(Number.isFinite)) return `${f.label}: not six numbers`;
      }
    }
    return null;
  }

  // -- the threads.js worker protocol (registerXBehavior(b) is expose(b), threads 1.7) --------

  function serializeError(err) {
    const e = err instanceof Error ? err : new Error(String(err));
    return { __error_marker: "$$error", name: e.name, message: e.message, stack: e.stack || "" };
  }

  function expose(behaviors) {
    root.addEventListener("message", (event) => {
      const msg = event.data;
      if (!msg || msg.type !== "run" || !msg.method) return;
      const fn = behaviors[msg.method];
      if (typeof fn !== "function") {
        root.postMessage({ type: "error", uid: msg.uid, error: serializeError(new Error(`no behavior ${msg.method}`)) });
        return;
      }
      let out;
      try {
        out = fn(...(msg.args || []));
      } catch (err) {
        root.postMessage({ type: "error", uid: msg.uid, error: serializeError(err) });
        return;
      }
      root.postMessage({ type: "running", uid: msg.uid, resultType: "promise" });
      Promise.resolve(out).then(
        (value) => root.postMessage({ type: "result", uid: msg.uid, complete: true, payload: value }),
        (err) => root.postMessage({ type: "error", uid: msg.uid, error: serializeError(err) }),
      );
    });
    root.postMessage({ type: "init", exposed: { type: "module", methods: Object.keys(behaviors) } });
  }

  // A ScriptBuilder crosses the worker boundary as {type: "$$ScriptBuilder", script, currentIndent}.
  function builder(script, indent) {
    const ls = lines(script);
    return { type: "$$ScriptBuilder", script: ls.length ? ls.join("\n") + "\n" : "", currentIndent: indent || 0 };
  }

  // The user-owned hooks of a node (<node>.hooks.js registers them under its tag).
  function hooks(tag) {
    return (root.UrcapHooks && root.UrcapHooks[tag]) || {};
  }

  // -- the page: a node's fields as a form (presenters only; never runs in a worker) ----------

  const CSS = `
    .ucg { font: 15px/1.45 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; color: #1f2a37; padding: 8px 12px; }
    .ucg h2 { margin: 0 0 4px; font-size: 20px; }
    .ucg .desc { margin: 0 0 12px; color: #4b5563; max-width: 720px; }
    .ucg .grid { display: grid; grid-template-columns: max-content minmax(220px, 420px); gap: 10px 16px; align-items: center; }
    .ucg label.k { font-weight: 600; }
    .ucg label.k small { font-weight: 400; color: #6b7280; }
    .ucg input[type=text], .ucg select { font: inherit; padding: 8px 10px; border: 1px solid #9aa5b1; border-radius: 6px; min-height: 40px; box-sizing: border-box; width: 100%; background: #fff; }
    .ucg input[type=checkbox] { width: 26px; height: 26px; }
    .ucg .help { grid-column: 2; margin-top: -6px; color: #6b7280; font-size: 13px; }
    .ucg .pose { display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; }
    .ucg .pose input { min-height: 36px; }
    .ucg button { font: inherit; padding: 8px 14px; min-height: 40px; border-radius: 6px; border: 1px solid #1f6feb; background: #1f6feb; color: #fff; }
    .ucg .status { margin-top: 12px; min-height: 1.4em; color: #b42318; }
    .ucg .status.ok { color: #1d7a46; }
    .ucg .row { display: flex; align-items: center; gap: 12px; min-height: 44px; }
    .ucg .row .label { flex: 1; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; color: #374151; }
  `;

  function esc(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }

  const fmtNum = (x) => String(x);

  // First value of an rxjs-style Observable (robotPositionService.getJointPositions()).
  function firstValue(observable, timeoutMs) {
    return new Promise((resolve, reject) => {
      if (!observable || typeof observable.subscribe !== "function") { reject(new Error("no stream from PolyScope")); return; }
      let done = false;
      const timer = setTimeout(() => { if (!done) { done = true; reject(new Error("PolyScope did not answer")); } }, timeoutMs || 5000);
      const sub = observable.subscribe({
        next: (v) => {
          if (done) return;
          done = true;
          clearTimeout(timer);
          try { sub && sub.unsubscribe && sub.unsubscribe(); } catch (e) { /* closed */ }
          resolve(v);
        },
        error: (e) => { if (!done) { done = true; clearTimeout(timer); reject(e); } },
      });
    });
  }

  // A PolyScope X pose in any shape it answers in → [x, y, z, rx, ry, rz] (m, rad).
  function poseArray(p) {
    if (Array.isArray(p)) return p.slice(0, 6).map(Number);
    if (p && p.position && p.orientation) {
      const a = p.position, o = p.orientation;
      return [a.x, a.y, a.z, o.x, o.y, o.z].map(Number);
    }
    if (p && "rx" in p) return [p.x, p.y, p.z, p.rx, p.ry, p.rz].map(Number);
    throw new Error("PolyScope answered a pose this URCap does not know");
  }

  // The TCP pose where the arm is now, through PolyScope X's robotPositionService (10.10+).
  async function currentTcpPose(api) {
    const rps = api && api.robotPositionService;
    if (!rps || typeof rps.getJointPositions !== "function" || typeof rps.convertJointPositionsToTcpPose !== "function") {
      throw new Error("this PolyScope X cannot report the TCP pose (needs 10.10 or later): type the numbers in");
    }
    const q = await firstValue(rps.getJointPositions());
    return poseArray(await rps.convertJointPositionsToTcpPose(q));
  }

  // Render `fields` into `el` with the values in `params` (edited in place); `save()` is called
  // after every change. Returns {refresh, status(text, ok), extra} — extra is a <div> under the
  // form for the node's hooks.
  function form(el, opts) {
    const { title, description, fields, params, save, api } = opts;
    el.innerHTML = `<style>${CSS}</style><div class="ucg"><h2>${esc(title)}</h2>`
      + (description ? `<p class="desc">${esc(description)}</p>` : "")
      + `<div class="grid"></div><div class="status"></div><div class="extra"></div></div>`;
    const grid = el.querySelector(".grid");
    const statusEl = el.querySelector(".status");
    const status = (text, ok) => { statusEl.textContent = text || ""; statusEl.className = "status" + (ok ? " ok" : ""); };
    const vals = () => valuesOf(fields, params);
    const check = () => { const why = problem(fields, vals()); status(why || ""); return why; };
    const commit = async (key, value) => {
      params[key] = value;
      if (!check()) await save();
    };
    const inputs = {};
    for (const f of fields) {
      const label = document.createElement("label");
      label.className = "k";
      label.innerHTML = esc(f.label) + (f.unit ? ` <small>(${esc(f.unit)})</small>` : "");
      grid.appendChild(label);
      let input;
      if (f.type === "bool") {
        input = document.createElement("input");
        input.type = "checkbox";
        input.addEventListener("change", () => commit(f.key, input.checked));
      } else if (f.type === "choice") {
        input = document.createElement("select");
        input.innerHTML = f.options.map((o) => `<option value="${esc(o.value)}">${esc(o.label)}</option>`).join("");
        input.addEventListener("change", () => commit(f.key, input.value));
      } else if (f.type === "pose") {
        input = document.createElement("div");
        input.className = "pose";
        const names = ["x (m)", "y (m)", "z (m)", "rx (rad)", "ry (rad)", "rz (rad)"];
        input.innerHTML = names.map((n, i) => `<input type="text" inputmode="decimal" data-i="${i}" title="${n}" placeholder="${n}" />`).join("")
          + `<button type="button" style="grid-column: span 3">Use the arm's current position</button>`;
        const parts = Array.from(input.querySelectorAll("input"));
        parts.forEach((p) => p.addEventListener("change", () => {
          const v = parts.map((q) => Number(q.value));
          if (v.every(Number.isFinite)) commit(f.key, v); else status(`${f.label}: six numbers`);
        }));
        input.querySelector("button").addEventListener("click", async () => {
          try {
            const pose = await currentTcpPose(api);
            await commit(f.key, pose);
            refresh();
            status(`${f.label}: set from the arm`, true);
          } catch (e) { status(e && e.message ? e.message : String(e)); }
        });
      } else {
        input = document.createElement("input");
        input.type = "text";
        if (f.type === "int") input.inputMode = "numeric";
        if (f.type === "float") input.inputMode = "decimal";
        input.addEventListener("change", () => {
          if (f.type === "string") { commit(f.key, input.value.replace(/["\r\n]/g, "")); return; }
          const n = Number(input.value);
          if (input.value.trim() === "" || !Number.isFinite(n) || (f.type === "int" && !Number.isInteger(n))) {
            status(`${f.label}: ${f.type === "int" ? "a whole number" : "a number"}`);
            return;
          }
          commit(f.key, n);
        });
      }
      inputs[f.key] = input;
      grid.appendChild(input);
      if (f.help) {
        const h = document.createElement("div");
        h.className = "help";
        h.textContent = f.help;
        grid.appendChild(h);
      }
    }
    function refresh() {
      const v = vals();
      for (const f of fields) {
        const input = inputs[f.key];
        if (f.type === "bool") input.checked = v[f.key];
        else if (f.type === "pose") input.querySelectorAll("input").forEach((p, i) => { p.value = fmtNum(v[f.key][i]); });
        else input.value = f.type === "float" || f.type === "int" ? fmtNum(v[f.key]) : v[f.key];
      }
      check();
    }
    refresh();
    return { refresh, status, extra: el.querySelector(".extra") };
  }

  // Load page scripts once per URL, however many presenters ask (a tag already in the page
  // may still be loading: everyone waits on the same promise).
  function loadScript(url) {
    const loads = (root.UrcapgenLoads = root.UrcapgenLoads || {});
    if (!loads[url]) {
      loads[url] = new Promise((resolve, reject) => {
        const s = document.createElement("script");
        s.src = url;
        s.onload = () => resolve();
        s.onerror = () => reject(new Error(`could not load ${url}`));
        document.head.appendChild(s);
      });
    }
    return loads[url];
  }

  const api = {
    version: VERSION, number, literal, raw, truthy, render, lines, valuesOf, typed, problem, expose, builder, hooks,
    esc, css: CSS, firstValue, poseArray, currentTcpPose, form, loadScript,
  };
  root.UrcapgenRuntimes[VERSION] = api;
  root.Urcapgen = api;
})(typeof self !== "undefined" ? self : globalThis);
