"""``urcap.toml`` → ``ps5/`` (Java/Swing OSGi sources) and ``psx/`` (PolyScope X web archive).

Ownership rule — the one thing to know before editing a URCap by hand:

* A file that starts with the ``GENERATED by urcapgen`` marker (and the JSON files listed in
  :data:`ALWAYS_GENERATED`) belongs to the generator. ``urcapgen gen`` rewrites it and deletes
  it when the spec no longer calls for it. Change ``urcap.toml`` instead.
* Every other file under ``ps5/`` and ``psx/`` belongs to you. The generator creates the hook
  files (``<Node>Hooks.java``, ``<node>.hooks.js``) once, with working defaults, and never
  touches them again. Extra classes or scripts you add are left alone (a PS5 class goes in
  the generated package's directory; a PSX script must be loaded by a hooks file).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from . import __version__
from .spec import Field, Node, Spec

MARK = "GENERATED by urcapgen"
ALWAYS_GENERATED = ("contribution.json", "en.json")
RUNTIME = resources.files("urcapgen") / "runtime"


@dataclass
class Out:
    path: str  # relative to the URCap's directory
    text: str
    owned: bool = False  # True: user-owned, written only if absent


# -- small helpers ------------------------------------------------------------------------------


def jstr(s: str) -> str:
    """A Java string literal."""
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def jnum(x: float | None) -> str:
    return "null" if x is None else f"{float(x)!r}"


def java_default(f: Field) -> str:
    if f.type == "int":
        return f"Integer.valueOf({int(f.default)})"
    if f.type == "float":
        return f"Double.valueOf({float(f.default)!r})"
    if f.type == "bool":
        return "Boolean.TRUE" if f.default else "Boolean.FALSE"
    if f.type == "pose":
        return "new double[] {" + ", ".join(repr(float(v)) for v in f.default) + "}"
    return jstr(str(f.default))


def java_def(f: Field) -> str:
    vals = labels = "null"
    if f.options:
        vals = "new String[] {" + ", ".join(jstr(o["value"]) for o in f.options) + "}"
        labels = "new String[] {" + ", ".join(jstr(o["label"]) for o in f.options) + "}"
    return (
        f"new Form.Def({jstr(f.key)}, {jstr(f.type)}, {jstr(f.label)}, {jstr(f.unit)}, {jstr(f.help)},\n"
        f"                    {jnum(f.min)}, {jnum(f.max)}, {java_default(f)}, {vals}, {labels})"
    )


def runtime_text(name: str, spec: Spec) -> str:
    text = (RUNTIME / name).read_text(encoding="utf-8")
    return text.replace("@@PACKAGE@@", spec.java_package).replace("@@VERSION@@", __version__)


def js_runtime() -> str:
    """How generated JS names its runtime: this urcapgen version's, never another URCap's."""
    return f'self.UrcapgenRuntimes["{__version__}"]'


def js_page_loader(hooks_file: str) -> str:
    """The presenters' loader: runtime first (by a plain tag; it may already be in the page
    from another presenter of this URCap), then this URCap's spec and the node's hooks
    through the runtime's shared once-per-URL loader."""
    return (
        "  const here = (document.currentScript && document.currentScript.src) || location.href;\n"
        "  const url = (name) => new URL(name, here).href;\n"
        "  let ready = null;\n"
        "  const libs = () => ready || (ready = (async () => {\n"
        f"    if (!(self.UrcapgenRuntimes || {{}})[\"{__version__}\"]) {{\n"
        "      const loads = (self.UrcapgenLoads = self.UrcapgenLoads || {});\n"
        '      const src = url("urcapgen-runtime.js");\n'
        "      loads[src] = loads[src] || new Promise((resolve, reject) => {\n"
        '        const s = document.createElement("script");\n'
        "        s.src = src; s.onload = () => resolve(); s.onerror = () => reject(new Error(`could not load ${src}`));\n"
        "        document.head.appendChild(s);\n      });\n"
        "      await loads[src];\n    }\n"
        f"    const U = {js_runtime()};\n"
        '    await U.loadScript(url("spec.js"));\n'
        f'    await U.loadScript(url("{hooks_file}"));\n'
        "    return U;\n"
        "  })());\n"
    )


def initials(spec: Spec) -> str:
    words = [w for w in spec.name.replace("-", " ").split() if w]
    s = "".join(w[0] for w in words[:2]).upper()
    return s or spec.id[:2].upper()


def icon_svg(spec: Spec, text: str) -> str:
    return (
        f"<!-- {MARK} -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48" height="48">'
        '<rect x="2" y="2" width="44" height="44" rx="10" fill="#1f6feb"/>'
        '<text x="24" y="31" font-family="Arial, Helvetica, sans-serif" font-size="18" font-weight="700" '
        f'fill="#ffffff" text-anchor="middle">{text}</text></svg>\n'
    )


def java_header(spec: Spec, what: str) -> str:
    return f"// {MARK} {__version__} from urcap.toml — {what}. Do not edit; change the spec.\npackage {spec.java_package};\n"


# -- PolyScope 5 --------------------------------------------------------------------------------


def ps5_bundle_properties(spec: Spec) -> str:
    desc = spec.description.replace("\n", " ") or spec.name
    lines = [
        f"# {MARK} {__version__} from urcap.toml. Do not edit; change the spec.",
        f"Bundle-SymbolicName={spec.symbolic_name}",
        f"Bundle-Name={spec.name}",
        f"Bundle-Vendor={spec.vendor_name}",
        f"Bundle-Copyright=Copyright (c) {spec.vendor_name}",
        f"Bundle-Version={spec.version}",
        f"Bundle-Activator={spec.java_package}.Activator",
        f"Bundle-Description={desc}",
        "URCapCompatibility-CB3=false",
        "URCapCompatibility-eSeries=true",
        f"compat.floor={spec.ps5_floor}",
    ]
    return "\n".join(lines) + "\n"


def ps5_activator(spec: Spec) -> str:
    imports = {"org.osgi.framework.BundleActivator", "org.osgi.framework.BundleContext"}
    regs = []
    if spec.installation:
        imports.add("com.ur.urcap.api.contribution.installation.swing.SwingInstallationNodeService")
        regs.append(
            f"        context.registerService(SwingInstallationNodeService.class, new {spec.installation.cls}Service(), null);"
        )
    for p in spec.programs:
        imports.add("com.ur.urcap.api.contribution.program.swing.SwingProgramNodeService")
        regs.append(f"        context.registerService(SwingProgramNodeService.class, new {p.cls}Service(), null);")
    if spec.toolbar:
        imports.add("com.ur.urcap.api.contribution.toolbar.swing.SwingToolbarService")
        regs.append("        context.registerService(SwingToolbarService.class, new ToolbarService(), null);")
    if spec.daemon:
        imports.add("com.ur.urcap.api.contribution.DaemonService")
        regs.insert(0, "        context.registerService(DaemonService.class, DAEMON, null);")
    body = "\n".join(regs)
    daemon_field = "    static final Daemon DAEMON = new Daemon();\n\n" if spec.daemon else ""
    return (
        java_header(spec, "registers every node with PolyScope 5")
        + "\n"
        + "".join(f"import {i};\n" for i in sorted(imports))
        + "\npublic class Activator implements BundleActivator {\n"
        + daemon_field
        + "    @Override\n    public void start(BundleContext context) {\n"
        + body
        + "\n    }\n\n    @Override\n    public void stop(BundleContext context) {\n    }\n}\n"
    )


def ps5_spec_class(spec: Spec, n: Node) -> str:
    defs = ",\n            ".join(java_def(f) for f in n.fields)
    after = ""
    if n.allows_children:
        after = (
            "\n    /** The script after the children (template, then the hooks). */\n"
            "    static String scriptAfter(Map<String, ScriptTemplate.Value> v) {\n"
            f"        return {n.cls}Hooks.scriptAfter(v, ScriptTemplate.render(SCRIPT_AFTER, v));\n"
            "    }\n"
        )
    return (
        java_header(spec, f"the {n.kind} node {n.id!r}: its fields and templates")
        + "\nimport java.util.Arrays;\nimport java.util.Collections;\nimport java.util.List;\nimport java.util.Map;\n\n"
        + f"final class {n.cls}Spec {{\n"
        + f"    static final String TITLE = {jstr(n.title)};\n"
        + f"    static final String DESCRIPTION = {jstr(n.description)};\n"
        + f"    static final String SCRIPT = {jstr(n.script)};\n"
        + f"    static final String SCRIPT_AFTER = {jstr(n.script_after)};\n"
        + f"    static final String LABEL = {jstr(n.label)};\n"
        + "    static final List<Form.Def> FIELDS = Collections.unmodifiableList(Arrays.<Form.Def>asList(\n"
        + (f"            {defs}" if n.fields else "")
        + "));\n\n"
        + f"    private {n.cls}Spec() {{\n    }}\n\n"
        + "    /** The node's script (template, then the hooks): what PolyScope runs. */\n"
        + "    static String script(Map<String, ScriptTemplate.Value> v) {\n"
        + f"        return {n.cls}Hooks.script(v, ScriptTemplate.render(SCRIPT, v));\n"
        + "    }\n"
        + after
        + "\n    /** Why the node is not ready (the spec's limits, then the hooks), or null. */\n"
        + "    static String problem(Map<String, ScriptTemplate.Value> v, String specProblem) {\n"
        + f"        return specProblem != null ? specProblem : {n.cls}Hooks.validate(v);\n"
        + "    }\n}\n"
    )


def ps5_program(spec: Spec, n: Node) -> list[Out]:
    d = spec.java_dir
    c = n.cls
    service = (
        java_header(spec, f"program node {n.id!r}: the service PolyScope 5 asks for it")
        + """
import com.ur.urcap.api.contribution.ViewAPIProvider;
import com.ur.urcap.api.contribution.program.ContributionConfiguration;
import com.ur.urcap.api.contribution.program.CreationContext;
import com.ur.urcap.api.contribution.program.ProgramAPIProvider;
import com.ur.urcap.api.contribution.program.swing.SwingProgramNodeService;
import com.ur.urcap.api.domain.data.DataModel;
import java.util.Locale;

"""
        + f"public class {c}Service implements SwingProgramNodeService<{c}Contribution, {c}View> {{\n"
        + "    @Override\n    public String getId() {\n"
        + f"        return {jstr(c)}; // saved programs find the node by this: never change it\n    }}\n\n"
        + "    @Override\n    public void configureContribution(ContributionConfiguration configuration) {\n"
        + f"        configuration.setChildrenAllowed({'true' if n.allows_children else 'false'});\n"
        + "        configuration.setUserInsertable(true);\n    }\n\n"
        + f"    @Override\n    public String getTitle(Locale locale) {{\n        return {c}Spec.TITLE;\n    }}\n\n"
        + f"    @Override\n    public {c}View createView(ViewAPIProvider apiProvider) {{\n"
        + f"        return new {c}View(apiProvider);\n    }}\n\n"
        + f"    @Override\n    public {c}Contribution createNode(\n"
        + f"            ProgramAPIProvider apiProvider, {c}View view, DataModel model, CreationContext context) {{\n"
        + f"        return new {c}Contribution(apiProvider, view, model);\n    }}\n}}\n"
    )
    view = (
        java_header(spec, f"program node {n.id!r}: its screen")
        + """
import com.ur.urcap.api.contribution.ViewAPIProvider;
import com.ur.urcap.api.contribution.program.swing.SwingProgramNodeView;
import com.ur.urcap.api.contribution.ContributionProvider;
import java.awt.BorderLayout;
import javax.swing.JPanel;

"""
        + f"public class {c}View implements SwingProgramNodeView<{c}Contribution> {{\n"
        + "    private final ViewAPIProvider api;\n    final Form form;\n\n"
        + f"    {c}View(ViewAPIProvider api) {{\n        this.api = api;\n"
        + f"        this.form = new Form(api, {c}Spec.FIELDS);\n    }}\n\n"
        + "    @Override\n"
        + f"    public void buildUI(JPanel panel, ContributionProvider<{c}Contribution> provider) {{\n"
        + "        panel.setLayout(new BorderLayout());\n"
        + "        JPanel fields = new JPanel();\n"
        + f"        form.build(fields, {c}Spec.TITLE, {c}Spec.DESCRIPTION);\n"
        + "        panel.add(fields, BorderLayout.NORTH);\n"
        + "        JPanel extra = new JPanel();\n"
        + "        panel.add(extra, BorderLayout.CENTER);\n"
        + f"        {c}Hooks.extendUI(extra, api);\n    }}\n}}\n"
    )
    children_write = ""
    if n.allows_children:
        children_write = (
            "        writer.writeChildren();\n"
            f"        for (String line : ScriptTemplate.lines({c}Spec.scriptAfter(v))) {{\n"
            "            writer.appendLine(line);\n        }\n"
        )
    contribution = (
        java_header(spec, f"program node {n.id!r}: its state, title and script")
        + """
import com.ur.urcap.api.contribution.ProgramNodeContribution;
import com.ur.urcap.api.contribution.program.ProgramAPIProvider;
import com.ur.urcap.api.domain.data.DataModel;
import com.ur.urcap.api.domain.script.ScriptWriter;
import com.ur.urcap.api.domain.undoredo.UndoableChanges;
import java.util.Map;

"""
        + f"public class {c}Contribution implements ProgramNodeContribution, Form.Store {{\n"
        + "    private final ProgramAPIProvider api;\n"
        + f"    private final {c}View view;\n"
        + "    private final DataModel model;\n\n"
        + f"    {c}Contribution(ProgramAPIProvider api, {c}View view, DataModel model) {{\n"
        + "        this.api = api;\n        this.view = view;\n        this.model = model;\n    }\n\n"
        + "    @Override\n    public DataModel model() {\n        return model;\n    }\n\n"
        + "    @Override\n    public void change(final Runnable r) {\n"
        + "        api.getProgramAPI().getUndoRedoManager().recordChanges(new UndoableChanges() {\n"
        + "            @Override\n            public void executeChanges() {\n                r.run();\n            }\n"
        + "        });\n    }\n\n"
        + f"    Map<String, ScriptTemplate.Value> values() {{\n        return Form.values(model, {c}Spec.FIELDS);\n    }}\n\n"
        + "    @Override\n    public void openView() {\n        view.form.refresh(this);\n    }\n\n"
        + "    @Override\n    public void closeView() {\n    }\n\n"
        + "    @Override\n    public String getTitle() {\n"
        + f"        if ({c}Spec.LABEL.isEmpty()) {{\n            return {c}Spec.TITLE;\n        }}\n"
        + "        try {\n"
        + f"            return {c}Spec.TITLE + \": \" + ScriptTemplate.render({c}Spec.LABEL, values(), true).trim();\n"
        + "        } catch (RuntimeException e) {\n"
        + f"            return {c}Spec.TITLE;\n        }}\n    }}\n\n"
        + "    @Override\n    public boolean isDefined() {\n"
        + f"        return {c}Spec.problem(values(), Form.problem(model, {c}Spec.FIELDS)) == null;\n    }}\n\n"
        + "    @Override\n    public void generateScript(ScriptWriter writer) {\n"
        + "        Map<String, ScriptTemplate.Value> v = values();\n"
        + f"        for (String line : ScriptTemplate.lines({c}Spec.script(v))) {{\n"
        + "            writer.appendLine(line);\n        }\n"
        + children_write
        + "    }\n}\n"
    )
    return [
        Out(f"ps5/src/{d}/{c}Spec.java", ps5_spec_class(spec, n)),
        Out(f"ps5/src/{d}/{c}Service.java", service),
        Out(f"ps5/src/{d}/{c}View.java", view),
        Out(f"ps5/src/{d}/{c}Contribution.java", contribution),
        Out(f"ps5/src/{d}/{c}Hooks.java", ps5_hooks(spec, n), owned=True),
    ]


def ps5_installation(spec: Spec, n: Node) -> list[Out]:
    d = spec.java_dir
    c = n.cls
    service = (
        java_header(spec, "the installation node: the service PolyScope 5 asks for it")
        + """
import com.ur.urcap.api.contribution.ViewAPIProvider;
import com.ur.urcap.api.contribution.installation.ContributionConfiguration;
import com.ur.urcap.api.contribution.installation.CreationContext;
import com.ur.urcap.api.contribution.installation.InstallationAPIProvider;
import com.ur.urcap.api.contribution.installation.swing.SwingInstallationNodeService;
import com.ur.urcap.api.domain.data.DataModel;
import java.util.Locale;

"""
        + f"public class {c}Service implements SwingInstallationNodeService<{c}Contribution, {c}View> {{\n"
        + "    @Override\n    public void configureContribution(ContributionConfiguration configuration) {\n    }\n\n"
        + f"    @Override\n    public String getTitle(Locale locale) {{\n        return {c}Spec.TITLE;\n    }}\n\n"
        + f"    @Override\n    public {c}View createView(ViewAPIProvider apiProvider) {{\n"
        + f"        return new {c}View(apiProvider);\n    }}\n\n"
        + f"    @Override\n    public {c}Contribution createInstallationNode(\n"
        + f"            InstallationAPIProvider apiProvider, {c}View view, DataModel model, CreationContext context) {{\n"
        + f"        return new {c}Contribution(apiProvider, view, model);\n    }}\n}}\n"
    )
    view = (
        java_header(spec, "the installation node: its screen")
        + """
import com.ur.urcap.api.contribution.ViewAPIProvider;
import com.ur.urcap.api.contribution.installation.swing.SwingInstallationNodeView;
import java.awt.BorderLayout;
import javax.swing.JPanel;

"""
        + f"public class {c}View implements SwingInstallationNodeView<{c}Contribution> {{\n"
        + "    private final ViewAPIProvider api;\n    final Form form;\n\n"
        + f"    {c}View(ViewAPIProvider api) {{\n        this.api = api;\n"
        + f"        this.form = new Form(api, {c}Spec.FIELDS);\n    }}\n\n"
        + f"    @Override\n    public void buildUI(JPanel panel, {c}Contribution contribution) {{\n"
        + "        panel.setLayout(new BorderLayout());\n"
        + "        JPanel fields = new JPanel();\n"
        + f"        form.build(fields, {c}Spec.TITLE, {c}Spec.DESCRIPTION);\n"
        + "        panel.add(fields, BorderLayout.NORTH);\n"
        + "        JPanel extra = new JPanel();\n"
        + "        panel.add(extra, BorderLayout.CENTER);\n"
        + f"        {c}Hooks.extendUI(extra, api);\n    }}\n}}\n"
    )
    daemon_start = daemon_open = ""
    if spec.daemon:
        daemon_start = "        Activator.DAEMON.start();\n"
        daemon_open = "        Activator.DAEMON.start();\n"
    contribution = (
        java_header(spec, "the installation node: its state and the program's preamble")
        + """
import com.ur.urcap.api.contribution.InstallationNodeContribution;
import com.ur.urcap.api.contribution.installation.InstallationAPIProvider;
import com.ur.urcap.api.domain.data.DataModel;
import com.ur.urcap.api.domain.script.ScriptWriter;
import java.util.Map;

"""
        + f"public class {c}Contribution implements InstallationNodeContribution, Form.Store {{\n"
        + "    @SuppressWarnings(\"unused\")\n    private final InstallationAPIProvider api;\n"
        + f"    private final {c}View view;\n"
        + "    private final DataModel model;\n\n"
        + f"    {c}Contribution(InstallationAPIProvider api, {c}View view, DataModel model) {{\n"
        + "        this.api = api;\n        this.view = view;\n        this.model = model;\n"
        + daemon_start
        + "    }\n\n"
        + "    @Override\n    public DataModel model() {\n        return model;\n    }\n\n"
        + "    @Override\n    public void change(Runnable r) {\n        r.run();\n    }\n\n"
        + f"    Map<String, ScriptTemplate.Value> values() {{\n        return Form.values(model, {c}Spec.FIELDS);\n    }}\n\n"
        + "    @Override\n    public void openView() {\n"
        + daemon_open
        + "        view.form.refresh(this);\n    }\n\n"
        + "    @Override\n    public void closeView() {\n    }\n\n"
        + "    @Override\n    public void generateScript(ScriptWriter writer) {\n"
        + ("        writer.appendLine(Daemon.PREAMBLE);\n" if spec.daemon else "")
        + f"        for (String line : ScriptTemplate.lines({c}Spec.script(values()))) {{\n"
        + "            writer.appendLine(line);\n        }\n    }\n}\n"
    )
    return [
        Out(f"ps5/src/{d}/{c}Spec.java", ps5_spec_class(spec, n)),
        Out(f"ps5/src/{d}/{c}Service.java", service),
        Out(f"ps5/src/{d}/{c}View.java", view),
        Out(f"ps5/src/{d}/{c}Contribution.java", contribution),
        Out(f"ps5/src/{d}/{c}Hooks.java", ps5_hooks(spec, n), owned=True),
    ]


def ps5_hooks(spec: Spec, n: Node) -> str:
    after = ""
    if n.allows_children:
        after = (
            "\n    /** The lines after the children. */\n"
            "    static String scriptAfter(Map<String, ScriptTemplate.Value> values, String rendered) {\n"
            "        return rendered;\n    }\n"
        )
    return (
        f"// Yours: urcapgen created this once and never rewrites it. Keep it in step with\n"
        f"// psx/{spec.psx_archive}/{n.id}.hooks.js — `urcapgen parity` holds both scripts to the same lines.\n"
        f"package {spec.java_package};\n\n"
        "import com.ur.urcap.api.contribution.ViewAPIProvider;\n"
        "import java.util.Map;\nimport javax.swing.JPanel;\n\n"
        f"/** Hand-written behavior of the {n.kind} node {n.id!r} on PolyScope 5. */\n"
        f"final class {n.cls}Hooks {{\n"
        f"    private {n.cls}Hooks() {{\n    }}\n\n"
        "    /** Extra Swing components under the generated form ({@code panel} is empty). */\n"
        "    static void extendUI(JPanel panel, ViewAPIProvider api) {\n    }\n\n"
        "    /** Why the node can't run, beyond the spec's min/max (null: it can). */\n"
        "    static String validate(Map<String, ScriptTemplate.Value> values) {\n        return null;\n    }\n\n"
        "    /** The node's URScript: {@code rendered} is the spec's template filled in. */\n"
        "    static String script(Map<String, ScriptTemplate.Value> values, String rendered) {\n"
        "        return rendered;\n    }\n"
        + after
        + "}\n"
    )


def ps5_toolbar(spec: Spec, n: Node) -> list[Out]:
    d = spec.java_dir
    service = (
        java_header(spec, "the toolbar button in PolyScope 5's header")
        + """
import com.ur.urcap.api.contribution.toolbar.ToolbarConfiguration;
import com.ur.urcap.api.contribution.toolbar.ToolbarContext;
import com.ur.urcap.api.contribution.toolbar.swing.SwingToolbarContribution;
import com.ur.urcap.api.contribution.toolbar.swing.SwingToolbarService;
import javax.swing.Icon;

public class ToolbarService implements SwingToolbarService {
    @Override
    public Icon getIcon() {
        return Icons.badge(30);
    }

    @Override
    public void configureContribution(ToolbarConfiguration configuration) {
        configuration.setToolbarHeight(400);
    }

    @Override
    public SwingToolbarContribution createToolbar(ToolbarContext context) {
        return new ToolbarContribution(context);
    }
}
"""
    )
    contribution = (
        java_header(spec, "the toolbar's panel")
        + """
import com.ur.urcap.api.contribution.toolbar.ToolbarContext;
import com.ur.urcap.api.contribution.toolbar.swing.SwingToolbarContribution;
import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class ToolbarContribution implements SwingToolbarContribution {
    private final ToolbarContext context;

    ToolbarContribution(ToolbarContext context) {
        this.context = context;
    }

    @Override
    public void buildUI(JPanel panel) {
        panel.setLayout(new BorderLayout());
"""
        + f"        JLabel head = new JLabel({jstr(n.title)});\n"
        + """        head.setFont(head.getFont().deriveFont(Font.BOLD, 18f));
        panel.add(head, BorderLayout.NORTH);
        JPanel extra = new JPanel();
        panel.add(extra, BorderLayout.CENTER);
        ToolbarHooks.extendUI(extra, context);
    }

    @Override
    public void openView() {
        ToolbarHooks.opened(context);
    }

    @Override
    public void closeView() {
        ToolbarHooks.closed(context);
    }
}
"""
    )
    hooks = (
        "// Yours: urcapgen created this once and never rewrites it.\n"
        f"package {spec.java_package};\n\n"
        "import com.ur.urcap.api.contribution.toolbar.ToolbarContext;\n"
        "import javax.swing.JLabel;\nimport javax.swing.JPanel;\n\n"
        "/** What the toolbar popup shows on PolyScope 5 (PolyScope X: the sidebar item's hooks). */\n"
        "final class ToolbarHooks {\n    private ToolbarHooks() {\n    }\n\n"
        "    /** Fill the popup ({@code panel} is empty). */\n"
        "    static void extendUI(JPanel panel, ToolbarContext context) {\n"
        f"        panel.add(new JLabel({jstr(n.description or spec.description or spec.name)}));\n    }}\n\n"
        "    static void opened(ToolbarContext context) {\n    }\n\n"
        "    static void closed(ToolbarContext context) {\n    }\n}\n"
    )
    icons = (
        java_header(spec, "the URCap's badge, drawn (no image resources)")
        + """
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;

final class Icons {
    private Icons() {
    }

    static Icon badge(int px) {
        BufferedImage img = new BufferedImage(px, px, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = img.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        g.setColor(new Color(0x1f, 0x6f, 0xeb));
        g.fillRoundRect(0, 0, px, px, px / 4, px / 4);
        g.setColor(Color.WHITE);
        g.setFont(new Font(Font.SANS_SERIF, Font.BOLD, px * 4 / 10));
        FontMetrics fm = g.getFontMetrics();
"""
        + f"        String s = {jstr(initials(spec))};\n"
        + """        g.drawString(s, (px - fm.stringWidth(s)) / 2, (px - fm.getHeight()) / 2 + fm.getAscent());
        g.dispose();
        return new ImageIcon(img);
    }
}
"""
    )
    return [
        Out(f"ps5/src/{d}/ToolbarService.java", service),
        Out(f"ps5/src/{d}/ToolbarContribution.java", contribution),
        Out(f"ps5/src/{d}/ToolbarHooks.java", hooks, owned=True),
        Out(f"ps5/src/{d}/Icons.java", icons),
    ]


def ps5_files(spec: Spec) -> list[Out]:
    d = spec.java_dir
    out = [
        Out("ps5/bundle.properties", ps5_bundle_properties(spec)),
        Out(f"ps5/src/{d}/Activator.java", ps5_activator(spec)),
        Out(f"ps5/src/{d}/ScriptTemplate.java", runtime_text("ScriptTemplate.java", spec)),
        Out(f"ps5/src/{d}/Form.java", runtime_text("Form.java", spec)),
    ]
    if spec.installation:
        out += ps5_installation(spec, spec.installation)
    for p in spec.programs:
        out += ps5_program(spec, p)
    if spec.toolbar:
        out += ps5_toolbar(spec, spec.toolbar)
    if spec.daemon:
        from . import daemon

        out += daemon.ps5_files(spec)
    return out


# -- PolyScope X --------------------------------------------------------------------------------


def psx_manifest(spec: Spec) -> str:
    lines = [
        f"# {MARK} {__version__} from urcap.toml. Do not edit; change the spec.",
        "metadata:",
        f'  vendorID: "{spec.vendor_id}"',
        f'  urcapID: "{spec.id}"',
        f'  vendorName: "{spec.vendor_name}"',
        f'  urcapName: "{spec.name}"',
        f"  version: {spec.version}",
        "artifacts:",
        "  webArchives:",
        f'  - id: "{spec.psx_archive}"',
        f'    folder: "{spec.psx_archive}"',
    ]
    if spec.daemon:
        from . import daemon

        lines += daemon.psx_manifest_lines(spec)
    return "\n".join(lines) + "\n"


def psx_spec_js(spec: Spec) -> str:
    nodes = {}
    for n in spec.nodes:
        nodes[spec.psx_tag(n)] = {
            "kind": n.kind,
            "id": n.id,
            "title": n.title,
            "description": n.description,
            "fields": [f.as_json() for f in n.fields],
            "script": n.script,
            "scriptAfter": n.script_after,
            "label": n.label,
            "allowsChildren": n.allows_children,
        }
    data = {
        "vendorID": spec.vendor_id,
        "urcapID": spec.id,
        "name": spec.name,
        "version": spec.version,
        "archive": spec.psx_archive,
        "appTag": spec.psx_tag() if spec.installation else None,
        "daemon": {"port": spec.daemon.port} if spec.daemon else None,
        "nodes": nodes,
    }
    return (
        f"// {MARK} {__version__} from urcap.toml. Do not edit; change the spec.\n"
        "// The URCap's spec for the presenters and workers. Every URCap shares PolyScope X's page,\n"
        "// so it merges into self.UrcapSpec: nodes by their (globally unique) tag, URCaps by vendor/id.\n"
        "(function (root) {\n"
        "  const R = (root.UrcapSpec = root.UrcapSpec || { nodes: {}, urcaps: {} });\n"
        f"  const spec = {json.dumps(data, indent=2)};\n"
        "  R.urcaps[spec.vendorID + \"/\" + spec.urcapID] = spec;\n"
        "  Object.assign(R.nodes, spec.nodes);\n"
        '})(typeof self !== "undefined" ? self : globalThis);\n'
    )


def psx_contribution(spec: Spec) -> str:
    app = []
    if spec.installation:
        t = spec.psx_tag(spec.installation)
        app.append(
            {
                "translationPath": "assets/i18n/",
                "behaviorURI": f"{t}.worker.js",
                "presenterURI": f"{t}.js",
                "componentTagName": t,
            }
        )
    progs = []
    for p in spec.programs:
        t = spec.psx_tag(p)
        progs.append(
            {
                "translationPath": "assets/i18n/",
                "iconURI": f"assets/icons/{t}.svg",
                "behaviorURI": f"{t}.worker.js",
                "presenterURI": f"{t}.js",
                "componentTagName": t,
                "categoryName": spec.id,
            }
        )
    side = []
    if spec.toolbar:
        t = spec.psx_tag(spec.toolbar)
        side.append(  # the keys of UR's global-variables-sidebar-item sample (SDK 6.5.65)
            {
                "name": t,
                "iconURI": f"assets/icons/{t}.svg",
                "presenterURI": f"{t}.js",
                "componentTagName": t,
                "behaviorURI": f"{t}.worker.js",
                "translationPath": "assets/i18n/",
                "size": "large",
            }
        )
    data = {
        "applicationNodes": app,
        "programNodes": progs,
        "smartSkills": [],
        "sidebarItems": side,
        "operatorScreens": [],
    }
    return json.dumps(data, indent=2) + "\n"


def psx_i18n(spec: Spec) -> str:
    data: dict = {}
    if spec.installation:
        n = spec.installation
        data["application"] = {
            "nodes": {spec.psx_tag(n): {"title": n.title, "supportiveText": n.description or spec.description}}
        }
    if spec.programs:
        data["program"] = {"tree": {"nodes": {spec.psx_tag(p): p.title for p in spec.programs}}}
    if spec.toolbar:
        data["sidebar-items"] = {spec.psx_tag(spec.toolbar): {"title": spec.toolbar.title}}
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def js_header(what: str) -> str:
    return f"// {MARK} {__version__} from urcap.toml — {what}. Do not edit; change the spec.\n"


def psx_program_worker(spec: Spec, n: Node) -> str:
    t = spec.psx_tag(n)
    return (
        js_header(f"program node {n.id!r}: its behaviors (PolyScope X web worker)")
        + f'importScripts("urcapgen-runtime.js", "spec.js", "{n.id}.hooks.js");\n\n'
        + "(() => {\n"
        + f'  const TAG = "{t}";\n'
        + f"  const U = {js_runtime()};\n  const S = self.UrcapSpec.nodes[TAG];\n"
        + "  const H = () => U.hooks(TAG);\n\n"
        + "  const defaults = () => U.valuesOf(S.fields, {});\n"
        + '  const fresh = () => ({ type: TAG, version: "1.0.0", allowsChildren: S.allowsChildren, parameters: defaults() });\n'
        + "  const vals = (node) => U.valuesOf(S.fields, node && node.parameters);\n\n"
        + "  function script(node, after) {\n"
        + "    const v = vals(node);\n"
        + "    const rendered = U.render(after ? S.scriptAfter : S.script, U.typed(S.fields, v));\n"
        + '    const hook = H()[after ? "scriptAfter" : "script"];\n'
        + "    return hook ? hook(v, rendered) : rendered;\n  }\n\n"
        + "  function problem(node) {\n"
        + "    const v = vals(node);\n"
        + "    return U.problem(S.fields, v) || (H().validate ? H().validate(v) : null);\n  }\n\n"
        + "  const depth = S.allowsChildren ? 1 : 0;\n"
        + "  U.expose({\n"
        + "    factory: async () => fresh(),\n"
        + "    programNodeLabel: async (node) => {\n"
        + "      if (!S.label) return [];\n"
        + "      try { return [{ type: \"primary\", value: U.render(S.label, U.typed(S.fields, vals(node)), true).trim() }]; }\n"
        + "      catch (e) { return []; }\n    },\n"
        + "    validator: async (node) => {\n"
        + "      const why = problem(node);\n"
        + "      return why ? { isValid: false, errorMessageKey: why } : { isValid: true };\n    },\n"
        + "    generateCodeBeforeChildren: async (node) => U.builder(script(node, false), depth),\n"
        + "    generateCodeAfterChildren: async (node) => U.builder(S.allowsChildren ? script(node, true) : \"\", -depth),\n"
        + "    allowsChild: async () => S.allowsChildren,\n"
        + "    upgradeNode: async (loaded) => ({ ...fresh(), ...(loaded || {}), parameters: { ...defaults(), ...((loaded && loaded.parameters) || {}) } }),\n"
        + "  });\n\n"
        + "  // the parity tests (node, outside PolyScope) call this\n"
        + "  self.UrcapScripts = self.UrcapScripts || {};\n"
        + "  self.UrcapScripts[TAG] = { script, problem };\n"
        + "})();\n"
    )


def psx_program_presenter(spec: Spec, n: Node) -> str:
    t = spec.psx_tag(n)
    return (
        js_header(f"program node {n.id!r}: its tree row and dialog (PolyScope X presenter)")
        + "// PolyScope X draws a program node's presenter inside its tree row; the form opens as a\n"
        + "// PolyScope dialog (dialogService.openCustomDialog) that saves through the row's API.\n"
        + "(() => {\n"
        + f'  const TAG = "{t}";\n  const DIALOG = TAG + "-dialog";\n'
        + js_page_loader(f"{n.id}.hooks.js")
        + "\n"
        + "  class Row extends HTMLElement {\n"
        + "    get contributedNode() { return this._node; }\n"
        + "    set contributedNode(v) { this._node = v; this.render(); }\n"
        + "    get presenterAPI() { return this._api; }\n"
        + "    set presenterAPI(v) { this._api = v; this.render(); }\n"
        + "    get robotSettings() { return this._rs; }\n    set robotSettings(v) { this._rs = v; }\n"
        + "    get programTree() { return this._tree; }\n    set programTree(v) { this._tree = v; }\n"
        + "    get applicationContext() { return this._ctx; }\n    set applicationContext(v) { this._ctx = v; }\n"
        + "    connectedCallback() { this.render(); }\n\n"
        + "    async render() {\n"
        + "      const U = await libs(), S = self.UrcapSpec.nodes[TAG];\n"
        + "      if (!this._node) return;\n"
        + "      const v = U.valuesOf(S.fields, this._node.parameters);\n"
        + '      let label = "";\n'
        + "      try { label = S.label ? U.render(S.label, U.typed(S.fields, v), true).trim() : \"\"; } catch (e) { label = String(e.message || e); }\n"
        + "      const why = U.problem(S.fields, v);\n"
        + "      this.innerHTML = `<style>${U.css}</style><div class=\"ucg\"><div class=\"row\">`\n"
        + "        + `<span class=\"label\">${U.esc(why || label)}</span><button type=\"button\">Edit</button></div></div>`;\n"
        + '      this.querySelector("button").addEventListener("click", () => this.open());\n    }\n\n'
        + "    async open() {\n"
        + "      const api = this._api;\n"
        + "      if (!api || !api.dialogService) return;\n"
        + "      const S = self.UrcapSpec.nodes[TAG];\n"
        + "      await api.dialogService.openCustomDialog(DIALOG, { node: this._node, api }, {\n"
        + '        title: S.title, dialogSize: "XL", confirmText: "Done", raiseForKeyboard: true,\n'
        + "      });\n"
        + "      this.render();\n    }\n  }\n\n"
        + "  class Dialog extends HTMLElement {\n"
        + "    get inputData() { return this._in; }\n"
        + "    set inputData(v) { this._in = v || {}; this.render(); }\n"
        + "    get presenterApi() { return this._dapi; }\n    set presenterApi(v) { this._dapi = v; }\n"
        + "    get afterOpen() { return this._ao; }\n    set afterOpen(v) { this._ao = v; }\n"
        + "    connectedCallback() { this.render(); }\n\n"
        + "    async render() {\n"
        + "      const node = this._in && this._in.node;\n"
        + "      if (!node || this._built === node) return;\n"
        + "      this._built = node;\n"
        + "      const U = await libs(), S = self.UrcapSpec.nodes[TAG];\n"
        + "      const api = this._in.api;\n"
        + "      node.parameters = node.parameters || {};\n"
        + "      const save = async () => {\n"
        + "        await api.programNodeService.updateNode(node);\n"
        + '        this.dispatchEvent(new CustomEvent("outputDataChange", { detail: node, bubbles: true }));\n      };\n'
        + "      const f = U.form(this, { title: S.title, description: S.description, fields: S.fields, params: node.parameters, save, api });\n"
        + "      const h = U.hooks(TAG);\n"
        + "      if (h.extendUI) h.extendUI(f.extra, { node, api, values: () => U.valuesOf(S.fields, node.parameters), save });\n"
        + "    }\n  }\n\n"
        + "  if (!customElements.get(TAG)) customElements.define(TAG, Row);\n"
        + "  if (!customElements.get(DIALOG)) customElements.define(DIALOG, Dialog);\n"
        + "})();\n"
    )


def psx_app_worker(spec: Spec, n: Node) -> str:
    t = spec.psx_tag(n)
    daemon_line = ""
    if spec.daemon:
        from . import daemon

        daemon_line = daemon.preamble_line(spec, daemon.psx_url(spec))
    return (
        js_header("the application node: its behaviors (PolyScope X web worker)")
        + f'importScripts("urcapgen-runtime.js", "spec.js", "{n.id}.hooks.js");\n\n'
        + "(() => {\n"
        + f'  const TAG = "{t}";\n'
        + f"  const U = {js_runtime()};\n  const S = self.UrcapSpec.nodes[TAG];\n"
        + "  const H = () => U.hooks(TAG);\n"
        + "  const defaults = () => U.valuesOf(S.fields, {});\n"
        + '  const fresh = () => ({ type: TAG, version: "1.0.0", parameters: defaults() });\n'
        + "  const vals = (node) => U.valuesOf(S.fields, node && node.parameters);\n\n"
        + "  function script(node) {\n"
        + "    const v = vals(node);\n"
        + "    const rendered = U.render(S.script, U.typed(S.fields, v));\n"
        + "    return H().script ? H().script(v, rendered) : rendered;\n  }\n"
        + "  function problem(node) {\n"
        + "    const v = vals(node);\n"
        + "    return U.problem(S.fields, v) || (H().validate ? H().validate(v) : null);\n  }\n\n"
        + "  U.expose({\n"
        + "    factory: async () => fresh(),\n"
        + "    upgradeNode: async (loaded) => ({ ...fresh(), ...(loaded || {}), parameters: { ...defaults(), ...((loaded && loaded.parameters) || {}) } }),\n"
        + "    downgradeNode: async (loaded, defaultNode) => defaultNode,\n"
        + f"    generatePreamble: async (node) => U.builder({json.dumps(daemon_line + chr(10)) + ' + ' if daemon_line else ''}script(node), 0),\n"
        + "  });\n\n"
        + "  self.UrcapScripts = self.UrcapScripts || {};\n"
        + "  self.UrcapScripts[TAG] = { script, problem };\n"
        + "})();\n"
    )


def psx_app_presenter(spec: Spec, n: Node) -> str:
    t = spec.psx_tag(n)
    return (
        js_header("the application node: its screen (PolyScope X presenter)")
        + "(() => {\n"
        + f'  const TAG = "{t}";\n'
        + js_page_loader(f"{n.id}.hooks.js")
        + "\n"
        + "  class App extends HTMLElement {\n"
        + "    get applicationNode() { return this._node; }\n"
        + "    set applicationNode(v) { const first = !this._node; this._node = v; if (first) this.render(); }\n"
        + "    get applicationAPI() { return this._api; }\n    set applicationAPI(v) { this._api = v; }\n"
        + "    get robotSettings() { return this._rs; }\n    set robotSettings(v) { this._rs = v; }\n"
        + "    get robotContext() { return this._rc; }\n    set robotContext(v) { this._rc = v; }\n"
        + "    connectedCallback() { this.render(); }\n\n"
        + "    async render() {\n"
        + "      if (!this._node || this._built === this._node) return;\n"
        + "      this._built = this._node;\n"
        + "      const U = await libs(), S = self.UrcapSpec.nodes[TAG];\n"
        + "      const node = this._node;\n"
        + "      node.parameters = node.parameters || {};\n"
        + "      const save = async () => { if (this._api) await this._api.applicationNodeService.updateNode(node); };\n"
        + "      const f = U.form(this, { title: S.title, description: S.description, fields: S.fields, params: node.parameters, save, api: this._api });\n"
        + "      const h = U.hooks(TAG);\n"
        + "      if (h.extendUI) h.extendUI(f.extra, { node, api: this._api, values: () => U.valuesOf(S.fields, node.parameters), save });\n"
        + "    }\n  }\n\n"
        + "  if (!customElements.get(TAG)) customElements.define(TAG, App);\n"
        + "})();\n"
    )


def psx_sidebar_presenter(spec: Spec, n: Node) -> str:
    t = spec.psx_tag(n)
    return (
        js_header("the sidebar item (PolyScope X's counterpart of the PolyScope 5 toolbar)")
        + "(() => {\n"
        + f'  const TAG = "{t}";\n'
        + js_page_loader("toolbar.hooks.js")
        + "\n"
        + "  class Side extends HTMLElement {\n"
        + "    get presenterAPI() { return this._api; }\n    set presenterAPI(v) { this._api = v; }\n"
        + "    get sidebarItem() { return this._item; }\n    set sidebarItem(v) { this._item = v; }\n"
        + "    get robotSettings() { return this._rs; }\n    set robotSettings(v) { this._rs = v; }\n"
        + "    connectedCallback() { this.render(); }\n"
        + "    disconnectedCallback() { const h = self.Urcapgen && self.Urcapgen.hooks(TAG); if (h && h.closed) h.closed(); }\n\n"
        + "    async render() {\n"
        + "      if (this._built) return;\n"
        + "      this._built = true;\n"
        + "      const U = await libs(), S = self.UrcapSpec.nodes[TAG];\n"
        + "      this.innerHTML = `<style>${U.css}</style><div class=\"ucg\"><h2>${U.esc(S.title)}</h2><div class=\"extra\"></div></div>`;\n"
        + "      const h = U.hooks(TAG);\n"
        + '      if (h.extendUI) h.extendUI(this.querySelector(".extra"), { api: this._api, item: this._item });\n'
        + "    }\n  }\n\n"
        + "  if (!customElements.get(TAG)) customElements.define(TAG, Side);\n"
        + "})();\n"
    )


def psx_sidebar_worker(spec: Spec, n: Node) -> str:
    t = spec.psx_tag(n)
    return (
        js_header("the sidebar item: its behaviors (PolyScope X web worker; registerSidebarBehavior)")
        + 'importScripts("urcapgen-runtime.js");\n\n'
        + f'const TAG = "{t}";\n'
        + f"{js_runtime()}.expose({{\n"
        + '  factory: async () => ({ type: TAG, version: "1.0.0" }),\n'
        + "  upgrade: async (loaded) => ({ type: TAG, version: \"1.0.0\", ...(loaded || {}) }),\n"
        + "});\n"
    )


def psx_hooks(spec: Spec, n: Node) -> str:
    t = spec.psx_tag(n)
    if n.kind == "toolbar":
        return (
            "// Yours: urcapgen created this once and never rewrites it.\n"
            "// What the sidebar item shows on PolyScope X (PolyScope 5: ToolbarHooks.java).\n"
            "(function (root) {\n"
            "  root.UrcapHooks = root.UrcapHooks || {};\n"
            f'  root.UrcapHooks["{t}"] = {{\n'
            "    // Fill the panel (an empty <div>). ctx.api: PolyScope's API for the sidebar.\n"
            "    extendUI(el, ctx) {\n"
            f"      el.textContent = {json.dumps(n.description or spec.description or spec.name)};\n"
            "    },\n"
            "    closed() {},\n"
            "  };\n"
            '})(typeof self !== "undefined" ? self : globalThis);\n'
        )
    after = ""
    if n.allows_children:
        after = "    // The lines after the children.\n    scriptAfter(values, rendered) {\n      return rendered;\n    },\n"
    return (
        "// Yours: urcapgen created this once and never rewrites it. Keep it in step with\n"
        f"// ps5/src/{spec.java_dir}/{n.cls}Hooks.java — `urcapgen parity` holds both scripts to the same lines.\n"
        "// Runs in the behavior worker (validate, script) and in the page (extendUI): no DOM in the first two.\n"
        "(function (root) {\n"
        "  root.UrcapHooks = root.UrcapHooks || {};\n"
        f'  root.UrcapHooks["{t}"] = {{\n'
        "    // Extra UI under the generated form. ctx: {node, api, values(), save()}.\n"
        "    extendUI(el, ctx) {},\n"
        "    // Why the node can't run, beyond the spec's min/max (null: it can). values: {key: value}.\n"
        "    validate(values) {\n      return null;\n    },\n"
        "    // The node's URScript: `rendered` is the spec's template filled in.\n"
        "    script(values, rendered) {\n      return rendered;\n    },\n"
        + after
        + "  };\n"
        '})(typeof self !== "undefined" ? self : globalThis);\n'
    )


def psx_files(spec: Spec) -> list[Out]:
    a = f"psx/{spec.psx_archive}"
    out = [
        Out("psx/manifest.yaml", psx_manifest(spec)),
        Out(f"{a}/contribution.json", psx_contribution(spec)),
        Out(f"{a}/urcapgen-runtime.js", runtime_text("urcapgen-runtime.js", spec)),
        Out(f"{a}/spec.js", psx_spec_js(spec)),
        Out(f"{a}/assets/i18n/en.json", psx_i18n(spec)),
    ]
    if spec.installation:
        n = spec.installation
        t = spec.psx_tag(n)
        out += [
            Out(f"{a}/{t}.js", psx_app_presenter(spec, n)),
            Out(f"{a}/{t}.worker.js", psx_app_worker(spec, n)),
            Out(f"{a}/{n.id}.hooks.js", psx_hooks(spec, n), owned=True),
        ]
    for p in spec.programs:
        t = spec.psx_tag(p)
        out += [
            Out(f"{a}/{t}.js", psx_program_presenter(spec, p)),
            Out(f"{a}/{t}.worker.js", psx_program_worker(spec, p)),
            Out(f"{a}/{p.id}.hooks.js", psx_hooks(spec, p), owned=True),
            Out(f"{a}/assets/icons/{t}.svg", icon_svg(spec, initials(spec))),
        ]
    if spec.toolbar:
        n = spec.toolbar
        t = spec.psx_tag(n)
        out += [
            Out(f"{a}/{t}.js", psx_sidebar_presenter(spec, n)),
            Out(f"{a}/{t}.worker.js", psx_sidebar_worker(spec, n)),
            Out(f"{a}/toolbar.hooks.js", psx_hooks(spec, n), owned=True),
            Out(f"{a}/assets/icons/{t}.svg", icon_svg(spec, initials(spec))),
        ]
    if spec.daemon:
        from . import daemon

        out += daemon.psx_files(spec)
    return out


# -- writing ------------------------------------------------------------------------------------


def files(spec: Spec) -> list[Out]:
    out: list[Out] = []
    if "ps5" in spec.platforms:
        out += ps5_files(spec)
    if "psx" in spec.platforms:
        out += psx_files(spec)
    if spec.daemon:
        from . import daemon

        out += daemon.shared_files(spec)
    return out


def is_generated(path: Path) -> bool:
    if path.name in ALWAYS_GENERATED:
        return True
    try:
        with path.open("r", encoding="utf-8") as fh:
            head = fh.read(200)
    except (OSError, UnicodeDecodeError):
        return False
    return MARK in head.split("\n", 2)[0] or MARK in "".join(head.split("\n", 2)[:2])


def plan(spec: Spec) -> dict:
    """What ``gen`` would do: ``{write: [...], create: [...], delete: [...], same: [...]}``."""
    root = spec.root
    wanted = files(spec)
    paths = {o.path for o in wanted}
    out: dict[str, list[str]] = {"write": [], "create": [], "delete": [], "same": []}
    for o in wanted:
        p = root / o.path
        if o.owned:
            if not p.exists():
                out["create"].append(o.path)
            continue
        if p.exists() and p.read_text(encoding="utf-8") == o.text:
            out["same"].append(o.path)
        else:
            out["write"].append(o.path)
    for top in ("ps5", "psx"):
        base = root / top
        if not base.is_dir():
            continue
        for p in sorted(base.rglob("*")):
            rel = p.relative_to(root).as_posix()
            if p.is_file() and rel not in paths and is_generated(p):
                out["delete"].append(rel)
    return out


def generate(spec: Spec, *, check: bool = False) -> dict:
    """Write the generated files (and create missing hook files). ``check``: write nothing."""
    p = plan(spec)
    if check:
        return p
    by_path = {o.path: o for o in files(spec)}
    for rel in p["write"] + p["create"]:
        dest = spec.root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(by_path[rel].text, encoding="utf-8")
    for rel in p["delete"]:
        (spec.root / rel).unlink()
    # prune directories the deletions emptied
    for top in ("ps5", "psx"):
        base = spec.root / top
        if base.is_dir():
            for d in sorted((x for x in base.rglob("*") if x.is_dir()), key=lambda x: -len(x.parts)):
                if not any(d.iterdir()):
                    d.rmdir()
    return p
